version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    env_file:
      - .env
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-app
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    command: npm run dev